//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Quanly
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sach()
        {
            this.sachduocmuas = new HashSet<sachduocmua>();
            this.sachduocthues = new HashSet<sachduocthue>();
            this.sachthuoctacgias = new HashSet<sachthuoctacgia>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public System.DateTime ngay_xuat_ban { get; set; }
        public decimal gia_ban { get; set; }
        public decimal gia_thue { get; set; }
        public int so_luong { get; set; }
        public string the_loai { get; set; }
        public decimal gia_nhap { get; set; }
        public string id_nxb { get; set; }
    
        public virtual NXB NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachduocmua> sachduocmuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachduocthue> sachduocthues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachthuoctacgia> sachthuoctacgias { get; set; }
    }
}
