//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Quanly
{
    using System;
    using System.Collections.Generic;
    
    public partial class sachduocthue
    {
        public int id { get; set; }
        public System.DateTime ngay_thue { get; set; }
        public Nullable<System.DateTime> ngay_tra { get; set; }
        public decimal gia_thue { get; set; }
        public System.DateTime created_date { get; set; }
        public string id_sach { get; set; }
        public string id_user { get; set; }
    
        public virtual sach sach { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
