//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Quanly
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taikhoan()
        {
            this.sachduocmuas = new HashSet<sachduocmua>();
            this.sachduocthues = new HashSet<sachduocthue>();
            this.sachthuoctacgias = new HashSet<sachthuoctacgia>();
            this.codes = new HashSet<code>();
        }
    
        public string id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public decimal sotienconlai { get; set; }
        public int phanquyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachduocmua> sachduocmuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachduocthue> sachduocthues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sachthuoctacgia> sachthuoctacgias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<code> codes { get; set; }
    }
}
